### ISSUE TITLE
Conversation tracking

### ISSUE THREAD

**Issue by patchandthat** [patchandthat/Yakka#6]
- [x] Initiate conversations, 2+ users
- [x] Send conversation messages
- [x] Leave conversation _(not doing)_
- [x] Invite new users to existing conversations _(not doing)_
- [ ] Optional server side conversation logging/monitoring
- [ ] Conversation history for clients

**Comment by patchandthat** [comment]
Thinking about this I sort of see clients having persistent ID's, and server conversation handlers storing their message histories, and using akka.persistence.  Conversations can time out after periods of inactivity, and be restored at a later time to recover the chat history.  Using this model you would never actually leave a conversation.

Obviously need some sort of limit to the length of history held in memory.
